Testing improvements
ONSdigital/census-rm-pubsub-adapter pull request #15
Opened 2020-06-03 10:36 UTC by AdamHawtin

# Motivation and Context
Uses the popular [Testify](https://github.com/stretchr/testify) module for test assertions, refactor and improve timeouts/contexts in tests.

# What has changed
* Add testify module
* Use testify asserts wherever applicable
* Move rabbit publishing related code out into separate file
* Tidy the go.mod

# How to test?
Should be zero regression, tests should still pass from command line/IDE. AT's should still pass

# Links
https://trello.com/c/SKxD063x/997-spike-pubsub-adapter-safe-rabbit-publishing-with-transactions-1-day

2020-06-05 07:31 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pubsub-Adapter - More thorough unit testing](https://trello.com/c/Pr28FGYJ/1015-pubsub-adapter-more-thorough-unit-testing)

2020-06-08 09:20 UTC, NickGrantONS commented on main_test.go
> +		if _, err := StartProcessors(timeout, cfg, make(chan error)); err != nil {
why doesn't this use `assert.NoErrorf`?

2020-06-08 09:20 UTC, NickGrantONS commented on main_test.go
>  		if messageId, err := publishMessageToPubSub(timeout, messageToSend, topic, project); err != nil {
why doesn't this use `assert.NoErrorf`?

2020-06-08 09:20 UTC, NickGrantONS commented on main_test.go
> +	if _, err := StartProcessors(timeout, cfg, make(chan error)); err != nil {
why doesn't this use `assert.NoErrorf`?

2020-06-08 09:20 UTC, NickGrantONS commented on main_test.go
> +	if _, err := publishMessageToPubSub(timeout, messageToSend, cfg.EqReceiptTopic, cfg.EqReceiptProject); err != nil {
why doesn't this use `assert.NoErrorf`?

2020-06-08 09:22 UTC, NickGrantONS commented on main_test.go
>  	if err != nil {
why doesn't this use `assert.NoErrorf`?

2020-06-08 09:23 UTC, NickGrantX requested changes
Inconsistent use of `assert.NoErrorf`?

2020-06-08 10:23 UTC, NickGrantX approved these changes
Nice tidy up

2020-06-08 10:46 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-06-08 10:54 UTC, merged