Processor Restarts
ONSdigital/census-rm-pubsub-adapter pull request #18
Opened 2020-06-11 06:30 UTC by AdamHawtin

# Motivation and Context
Enable processor restarts on errors from the rabbit channels and pubsub receiver so that the entire app is not immediatelly killed.

# What has changed
* Attempt to restart processors on errors on the error channel
* Send rabbit channel errors to the error channel
* Improve the readiness file handling so that the app shows not ready while failing to restart a processor
* Use a configurable timeout on restarting (should only keep one of this change or the readiness file work)
* Introduce a short delay on showing ready to give the processors time to actually attempt connection

# How to test?
Run the app, try killing a rabbit connection or deleting a pubsub subscription it uses, it should attempt restart.

# Links
https://trello.com/c/ObrXF2L5/1012-tech-session-restart-pubsub-processors

2020-06-11 06:30 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [tech session: Restart pubsub processors](https://trello.com/c/ObrXF2L5/1012-tech-session-restart-pubsub-processors)

2020-06-15 07:45 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [PubSub Adapter - Restart Processors on errors](https://trello.com/c/6a2WnydH/1048-pubsub-adapter-restart-processors-on-errors)

2020-07-02 12:22 UTC, NickGrantONS commented on main.go
> +	startupTimer, cancel := context.WithTimeout(ctx, 5*time.Second)
Hard coded. Probably OK but we've tended to avoid hard coding, often. Could use a constant at least?

2020-07-02 12:33 UTC, NickGrantONS commented on main_test.go
> +	// Grab one of it's rabbit channels and subscribe to it's close notifications
*its 🤣

2020-07-02 13:43 UTC, NickGrantX approved these changes
Awesome

2020-07-03 06:22 UTC, davidmort requested changes

2020-07-03 06:22 UTC, davidmort commented on config/config.go
> +	ProcessorStartUpTimeSeconds int    `envconfig:"PROCESSOR_START_UP_TIME_SECONDS default:"5"`
```suggestion
	ProcessorStartUpTimeSeconds int    `envconfig:"PROCESSOR_START_UP_TIME_SECONDS" default:"5"`
```

2020-07-06 10:42 UTC, davidmort approved these changes

2020-07-06 10:44 UTC, davidmort commented
this works quite nicely now, did some chaos testing in my k8s cluster with dropping the network connection, even managed to prove it can run with a sub set of the processors working whilst the other's were trying to re-connect to rabbitmq (as that particular rabbit node was down)

great work 👍

2020-07-07 07:33 UTC, merged