Structured logging
ONSdigital/census-rm-pubsub-adapter pull request #8
Opened 2020-05-05 08:19 UTC by AdamHawtin

# Motivation and Context
We need the pubsub adapter to use structured logging so that log entries can be searched on and used for metrics in GKE/stackdriver/grafana.

# What has changed
* Configure zap structured logger at startup
* Use zap structured logging
* Add LOG_LEVEL environment variable to set the service log level

# How to test?
Try running the service at different log levels (e.g. INFO, DEBUG, WARN, ERROR).

# Links
https://trello.com/c/OXBw9jhY/908-pubsub-adapter-structured-logging-5

2020-05-05 08:22 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Pubsub Adapter - Structured Logging (5?)](https://trello.com/c/OXBw9jhY/908-pubsub-adapter-structured-logging-5)

2020-05-05 08:35 UTC, davidmort requested changes

2020-05-05 08:35 UTC, davidmort commented on main.go
> +		logger.Logger.Errorw("OS Signal Received", "signal", sig.String())
this feels more like INFO not an ERROR as receiving the shutdown signal is expected

2020-05-05 08:35 UTC, davidmort commented on main.go
> +	logger.Logger.Error("Shutting Down")
similar to the comment above, this feels more like an INFO thing

2020-05-05 08:35 UTC, davidmort commented on main.go
> +	logger.Logger.Error("Shutdown complete")
same as the comment above, feels like an INFO thing

2020-05-05 12:28 UTC, NickGrantX approved these changes
Looks nice 👍

2020-05-07 08:11 UTC, davidmort approved these changes

2020-05-07 08:11 UTC, merged